README-BR.md, README.md
It was detected some mistakes and warnings with plugin Markdown Lint in the readmes
This pull request corrects it
=> Format and fix Readme Markdown

README-BR.md, README.md
- [markdownlint](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint): Markdown linting and style checking for Visual Studio Code
=> Add Markdownlink extension

README-BR.md, README.md
- [Git Graph](https://marketplace.visualstudio.com/items?itemName=mhutchie.git-graph): View a Git Graph of your repository, and perform Git actions from the graph.
=> Add Git Graph Extension

README-BR.md, README.md
Added:
- Regex101
- JSONLint
- Conventional Commits
- gitignore.io
=> Added four web tools

README-BR.md, README-ES.md, README.md
Added a spanish version of this repository.
- All files now present their alternative language versions inside a `list` element.
=> Add Spanish (LatAm) version

README.md
Added the following tools
- DB Fiddle, Can I Use and carbon in web tools,
- Agent Ransack and Fiddler in desktop tools
=> Added new web tools and desktop tools

README.md
**About This PR**
- Added Code Playground Details and their Use
- VS Code **GitLens** added
=> Code Playground

README.md
=> Basic commonly used git commands

README-BR.md, README-ES.md, README.md
O Python Tutor ajuda as pessoas a superar uma barreira fundamental ao aprendizado de programação: entender o que acontece quando o computador executa cada linha de código em Python, Java, C, C++, JavaScript e Ruby.
=> Adicionada a ferramenta web Python Tutor

README-BR.md, README-ES.md, README.md
This PR aims to add the following to the list of VSCode extensions
- REST client and 
- Code Runner
=> Add some VSCode extensions

README-BR.md, README.md
I added both [Gerador de CPF](https://geradordecpf.org) and [Oh Shit, Git!?](https://ohshitgit.com) to the list.
Now you can generate CPFs faster and get out of a tight spot in Git. 😉
=> Add geradordecpf.org and Oh Shit, Git!?

vscode-extensions.md
- better comments
- #region folding for vscode
- todo tree
=> add three new vscode extensions

README.md
A tool for converting files into other formats
=> Added Convertio

README.md
Added new tools and libraries to help developers. To contribute to the developer community in various programming languages.
=> Added new tools and libraries to help developers.

vscode-extensions.md
Added SwaggerViewer as VS Code extension
=> Added SwaggerViewer as VS Code extension

README.md
=> Added SourceTree to Desktop Tools section.

README.md
=> Added iTerm2 to Desktop Tools section.

README.md
=> Added pgAdmin to Developer Tools section.

README.md
=> Added Homebrew to Desktop Tools section.

README.md
Added details of new desktop tools i.e. CodeLobster
=> Added new Desktop Tools - CodeLobster

README.md
added get waves for web design
=> added Get Waves

README.md
added DBDiagram for draw ER diagrams by writing code
=> added DBDiagram

vscode-extensions.md
Hi,. I has add 4 VS Code extension, thanks :)
=> add four useful Visual Studio Code Extension which is always I use when coding

README.md
added a git GUI recommendation
=> added a new desktop app recomendation

README.md
Added the git Explorer web app, this app is a helper to find git commands(or learn)
=> added new web tool

CONTRIBUTING.md
changed from cloning directly to fork
=> fix: the explanation on how to contribute with the project and its flow

README.md
Added postwoman to web tools section, postwoman is a tool like postman and insomnia but simpler.
=> added postwoman to web tools section

vscode-extensions.md
A awesome plugin, perfect for those who use vscode in more than one computer
=> add settings-sync

README.md
This is a awesome app, which I would recommend even for those who use git for long time.
It teachs you by showing some concepts, examples, and then exercises.
=> add git branch

README.md
Added PyCharm to the list of Deskop tools for devs.
=> Added pycharm to dev tools (desktop)

README.md
=> Added tableplus db tool

vscode-extensions.md
add five vscode extensions to list
=> add vscode extensions

commands.md, vscode-extensions.md
Added several git commands to the useful commands to help first timers like myself.
Also added the autosave on window switch vscode extension
=> Added to useful cmds and vscode extensions

README.md
=> Add new tool - AWS Cloud9

vscode-extensions.md
Added bracket pair extension to vscode
=> Added custom extension

README.md
=> added asciinema

README.md
A project management platform for agile developers & designers and project managers who want a beautiful tool that makes work truly enjoyable.
More about it here: https://taiga.io/
=> Added Taiga

README.md
Hello, I added extendsclass to Web Tools (I am the founder of extendsclass.com).
=> Added extendsclass to web tools

README.md
- Shield.io: Create beautiful badges for your markdown document.
- ASCII Art Image Generator: This free online Ascii Art creator allows you to convert images to color or monochrome Ascii Art.
=> Add Shield.io and ASCII Art Image Generator in topic web tools

README.md
- Add Hackmd.io (https://hackmd.io/)
=> Add Hackmd.io

README.md
It adds JSON Utils, TabsToSpaces, Epoch Converter, XML Viewer, NimbleText and BASE64 Decode
=> Add six more online tools

vscode-extensions.md
added dotENV to list of useful vs-code extensions for developers.
dotENV supports syntax highlighting for environment settings (.env files)
=> added extension dotENV

README.md
I've added a tool that I consider one of the bests for managing all the process of creating an app, since documentation to deploy.
=> Azure DevOps

README.md
Add two IDEs to the Desktop Tools list.
=> Add desktop tools

vscode-extensions.md
Adds a new vscode extension: "GitHub Pull Requests and Issues"
=> Adds a new vscode extension

README.md
This PR add a new tool (Coolors) in the web tools list.
=> Docs: Add Coolors in the Web Tools List

README.md
Tables helps teams easily track & automate tasks, enabling them to save time and work smarter.
https://tables.area120.google.com/about
=> Add Google Tables

README.md
I use these tools myself very often. Really help debugging and sharing/presenting bugs/features with team members much faster.
=> Add 'Fake Filler Chrome Extension' and 'Peek'

commands.md, vscode-extensions.md
Added React code snippets, Peacock, and TabNine to vscode extensions.
=> Add VS code extensions

commands.md
Added a few more useful git commands
=> Add git commands to commands.md

README.md
=> Added Flutter

README.md
I added Windows Subsystem for Linux (WSL) to README.md. WSL allows users to run a Linux shell and different Linux commands on Linux without having to install a hypervisor and setting up a VM.
=> Added new tool (WSL2) to README.md

README.md
Fixed the conflict by linter in the last PR. New tools added to README.md
=> Fix conflict new web tools

README.md, code-playgrounds.md, vscode-extensions.md
This one is my first...i'll add one more soon. Thank U
=> added vs code extension

README.md
I have added ohmyzsh which is a framework for zsh shell and Tmux (terminal multiplexer)
=> Added ohmyzsh and tmux

vscode-extensions.md
Hi!
A sugestion for the vs-code extension.
=> Insert Browser-Preview

README.md
Hello, I just add 
* Eclipse IDE link (usefull IDE for Java Developer) 
* yEd Graph Editor (nice to have tool for diagrams etc)
=> Adding Eclipse and yEd

README.md, commands.md
Added Adobe XD and Expo in main README.md. Also added simple ```ssh``` command under ```commands.md```
=> Added Adobe XD, EXPO, and ssh (command)

README.md
=> added new tool - terraform

README.md
Removed duplicate item `Color Hunt` in README.md
=> Remove duplicate item in README.md

vscode-extensions.md
Added Indented Block Highlighting in `vscode-extensions.md`
=> Add Indented Block Highlighting

README.md
added db engines web tool that ranks dbms'
=> Add DB-engines

README.md
Added "meld" and "barrier" at line 132 and 133.
Amazing desktop tools that I will definitely install the first thing after a fresh Linux/Mac/Windows installation.
=> Added "meld" and "barrier" to README.MD

README.md
- Added Screely.com, which is a website for generating quick browser mockups.
- Added Marcdown, a useful lightweight markdown viewer and editor.
- Renamed Postwoman to Hoppscotch (see https://postwoman.io)
=> [HACKTOBERFEST] Add 2 useful tools

vscode-extensions.md
- add 3 useful VSCode extensions
=> [Hacktoberfest] add VSCode extensions

README.md
Add info about helm package manager for Kubernetes
=> Add info about helm site

README.md
Scoop is a lot like Chocolatey and brew but has the benefit of not requiring elevated permissions
=> Add scoop to desktop tools

README.md
- add jetbrains IDEs
- add a note on how to get a license (legitimately) free
=> add jetbrains IDEs

chrome-extensions.md, code-playgrounds.md, vscode-extensions.md
Added code playground (Google Colab), vscode extension (React native tools) and chrome extension (WhatFont and Colorzilla).
=> Added code playground, vscode extension and chrome extension

desktop-tools.md
Last pull request it was missing a link but the the the pull request was closed before I provide the changes because I wasn't at home. This pull request adds "Process Explorer" which is a task manager for Windows which I use in my daily work and recomend.
Best regards.
=> Add process explorer

web-tools.md
Added www.tinkercad.com to web-tools.md.
=> Added Tinkercad to web-tools.md

code-playgrounds.md, desktop-tools.md
=> Added nmap and Rust playground

commands.md
=> Add rmdir to commands.md

web-tools.md
=> Added JSON Formatter to web-tools

web-tools.md
[Gitmoji](https://gitmoji.carloscuesta.me/) is an pattern for commit messages that use emojis
=> added a gitmoji! 🎉

desktop-tools.md
=> Added cmder to desktop-tools

web-tools.md
=> added a new tool! 🎉

web-tools.md
I have added https://coggle.it/ to web-tools.md . Coggle is a web app which helps to make branched tree like structures to visualize ideas and mind maps.
=> added coggle.it to web-tools.md

chrome-extensions.md, vscode-extensions.md
Added wappalyzer to chrome extensions
Added Code time to vs code extensions
=> added wappalyzer/ Code Time

chrome-extensions.md, desktop-tools.md, web-tools.md
Added tools and websites for chrome-extensions, desktop and web tools.
=> Added tools and websites for chrome-extensions, desktop and web tools

vscode-extensions.md
=> Added Auto Rename Tag to VSCode Extensions

commands.md
=> add terminal history command

desktop-tools.md
- Added the NeoVim editor and Starship Prompt shell
- Created Topics to organize the links. The topics are: IDE/Text Editor, Infrastucture/DevOps, Bashs/Terminals/Consoles/Prompts, Version Control, Utils, Debug/Security, Database, Package Manager, Mobile and Browser.
-Added the browsers Chromium, Firefox Dev and Chrome Dev in the Browser Topic
=> Changes in desktop-tools.md

chrome-extensions.md
The fastest and easiest way to check, copy and edit CSS.
=> Add CSS Scan

desktop-tools.md
[DockStation](https://dockstation.io/) is a developer-centric application for managing projects based on Docker.
=> Add DockStation

web-tools.md
3Cols is a cloud based snippet manager which can be used to store, share and collaborate on your code snippets. All features on the app are free. Full disclaimer I am one of the developers on this project, but recently the user base has been growing and I think it is a tool a lot of developers could benefit from.
=> Added 3Cols

web-tools.md
=> Added Sonarqube in the list

commands.md
Added docker commands to
1. Login to docker hub registry
2. List of commands in Docker
3. Get docker version information
=> added new docker commands!

chrome-extensions.md
VisBug is an open source web design debug tools built with JavaScript: a FireBug for designers. With this, a user can edit any webpage, in any state.
=> Add VisBug under chrome-exetensions.md

desktop-tools.md
=> added a new tool - MacDown

web-tools.md
=> Bubbly page added :heavy_check_mark:

web-tools.md
=> added windframe

vscode-extensions.md
=> chore: add vscode extension

vscode-extensions.md
[Bracket Pair Colorizer](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer) | Extension that hightlights the end the matching brackets, whether in a function, array, or object!
[HTML Preview](https://marketplace.visualstudio.com/items?itemName=tht13.html-preview-vscode) | The ability to view HTMl locally.
These are the two tools I have added @lucasgdb . Thanks.
=> Added 2 tools

web-tools.md
=> new tools added :heavy_check_mark:

chrome-extensions.md
Added a chrome extension that can find anyone's personal and business emails and even phone numbers.
=> Added Aeroleads Chrome Extension

chrome-extensions.md
Taper monkey is very helpful chrome extension. Using this users can run their own custom scripts on one or multiple sites when they are loaded.
=> Added Tapermonkey to list of chrome extensions. This extension helps in running custom scripts.

web-tools.md
Added [JSON Crack](https://jsoncrack.com/), a very easy to use tools to understand your JSON data structure
=> Updated web-tools with JSONCrack

desktop-tools.md
Joplin is an open source note-taking app. Capture your thoughts and securely access them from any device.
=> Updated desktop-tools with Joplin

web-tools.md
- an online arduino simulator called wokwi.
https://wokwi.com/
=> Added web tool

chrome-extensions.md
Added **WhatRuns** extension to the _chrome-extensions_ list. This extension helps identify technologies used on any website.
=> Added WhatRuns chrome extension

chrome-extensions.md
Added a pretty useful Chrome Extension for Web-Developers.
=> added new chrome extension

chrome-extensions.md
=> added a new tool!

chrome-extensions.md
Added link to Raindrop.io. A bookmark management tool that allows you to quickly save webpages as bookmarks, save highlights, save tabs, etc. Furthermore, it has a web application that allows to view your content in an intuitive way.
=> Added link to Raindrop.io.

web-tools.md
Please review and merge it. (Hacktoberfest 2022)
=> Added Google Fonts as Web Tools

web-tools.md
Added new web tool named Codingame (https://www.codingame.com) with this description : CodinGame is a challenge-based training platform for programmers where you can improve your coding skills with fun exercises. Available for developers and recruiters.
This PR has been created for the Hacktoberfest. If possible, I would like the labels of this contest to be associated with this PR
=> Added codingame

web-tools.md
Only the last one (which has a better description) has been left.
This PR has been created for the Hacktoberfest. If possible, I would like the labels of this contest to be associated with this PR.
=> Removed duplicates "Coolors.com"

web-tools.md
Added new web tool named codethesaur.us (https://codethesaur.us/) with this description : Compare language components from languages you know and don't know, or just use it as a language reference cheat sheet.
This PR has been created for the Hacktoberfest. If possible, I would like the labels of this contest to be associated with this PR
=> Added codethesaur.us

web-tools.md
I have added some more web tools. Please review and merge it. THANKS!!
=> Added some web tools

web-tools.md
Please review and merge it. (Hacktoberfest 2022)
=> Added Code-Chef as web-tools

web-tools.md
Scrimba allows you to code along in real time using an on-screen editor along with the developer curriculum tutorials and offers free as well as paid courses for web development.
=> update: Add Scrimba to web-tools.md

web-tools.md
The Odin Project offers a free full-stack developer curriculum
=> update: Add Odin Project to web-tools.md

chrome-extensions.md
I added the tool Corporate Ipsum to the list of chrome extensions
=> added Corporate Ipsum to chrome-extensions

desktop-tools.md
Added pip to package managers in desktop-tools.md
=> Added pip to package managers in desktop-tools.md

chrome-extensions.md
Added Salesforce Metadata Finder to chrome-extensions.md
=> Added Salesforce Metadata Finder to chrome-extensions.md

android-apps.md
Sorted items in android-apps.md in alphabetical order.
=> Sorted items in android-apps.md

web-tools.md
Added a UI/UX designer in web tools (hacktoberfest)
=> feat: Added web tool

desktop-tools.md
Hi, could you merge my PR please?
=> Add Traefik - Open-Source Edge Router

README.md, productivity-apps.md
Added **Notion** as productivity app for developers.
=> Added Productivity Apps 🚀 section for devs

web-tools.md
Add **App Icon Resizer** a simple web based service to resize your app icon to all needed resolutions
=> add App Icon Resizer to web-tools

web-tools.md
Add [code magic](https://code-magic.vercel.app/)
=> feat: add code magic

web-tools.md
Adding a free tool we built recently.
=> Add DebugBear

chrome-extensions.md
Added chrome extension "AdBlock" for blocking ads and pop ups.
=> Added a chrome extension

productivity-apps.md
Pieces is an intelligent, interactive, and indispensable hub for small developer materials and essential workflow context.
=> Pieces for developers
